### ISSUE TITLE
原本程序使用这个之后无法启动？

### ISSUE THREAD

**Issue by SharkIng** [sanddudu/ghost-upyun#1]
原本用的是Ghost的原版但是希望可以用UPYUN所以按照这个修改了
结果无法启动了，什么原因呢？

**Comment by sanddudu** [comment]
我推荐直接使用这个项目里的代码，因为您自主修改可能会漏掉某些内容
我猜测是您没有在配置文件里加入对应的设置，你可以参考 config.example.js 的内容。
如果可以的话，请附上错误信息。

**Comment by sanddudu** [comment]
0.5.9 版适配已经发布，npm 同步更新
